apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: github-add-pull-request
spec:
  workspaces:
  - name: config
  - name: github-secret
  params:
  - name: PULL_REQUEST_BODY
    description: The body to be used for the pull request
    type: string
    default: ""
  - name: PULL_REQUEST_TITLE
    description: Title of the pull request
    type: string
    default: "Pull request created by Tekton task github-add-pull-request"
  - name: GITHUB_REPO_CONFIGMAPKEY
    description: The github owner/repo to use
    type: string
  - name: GIT_BRANCH_HEAD
    description: The branch to pull from
    type: string
    default: approve
  - name: GIT_BRANCH_BASE
    description: The branch to pull into
    type: string
    default: main
  steps:
  - name: create-pull-request
    image: registry.redhat.io/ubi9-minimal:9.5
    script: |
      GITREPO=$(cat $(workspaces.config.path)/$(params.GITHUB_REPO_CONFIGMAPKEY))
      # GIT_OPS_REPO_PROD_URL - https://gitea-route-vp-gitea.apps.mcg-hub.aws.validatedpatterns.io/gitea_admin/industrial-edge
      BASE=$(echo $GITREPO | cut -d'/' -f1-3)
      END=$(echo $GITREPO | cut -d'/' -f4-)
      URL="${BASE}/api/v1/repos/${END}/pulls"
      curl -k --fail-with-body -v -u "$(cat $(workspaces.github-secret.path)/username):$(cat $(workspaces.github-secret.path)/password)" \
        -H "Content-Type: application/json" -X POST \
        --data '{"base": "$(params.GIT_BRANCH_BASE)", "title": "$(params.PULL_REQUEST_TITLE)", "head": "$(params.GIT_BRANCH_HEAD)"}' "${URL}"
