apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gitops-imagetag
spec:
  workspaces:
  - name: gitrepos
    description: The git repo will be cloned onto the volume backing this workspace
  - name: config
  params:
  - name: CONFIGMAP_PREFIX
    type: string
  - name: ENVIRONMENT
    type: string
    default: TEST
    description: TEST or PROD
  - name: TAG
    description: the VERSION tag
    type: string
  - name: subdirectory
    description: subdirectory inside the "gitrepos" workspace to clone the git repo into
    type: string
    default: "ops"
  steps:
  - name: patch-values
    image: {{ .Values.yq.image }}
    script: |
      set -x
      TAG_VALUE=$(params.TAG)
      VALUES_PATH="$(cat $(workspaces.config.path)/$(params.CONFIGMAP_PREFIX)_$(params.ENVIRONMENT)_VALUES_PATH)"
      ls -al $VALUES_PATH
      YAML_PATH="$(cat $(workspaces.config.path)/$(params.CONFIGMAP_PREFIX)_YAML_PATH)"
      echo "$(params.CONFIGMAP_PREFIX)_YAML_PATH) : $YAML_PATH"
      UPDATE_FLAG_PATH="$(cat $(workspaces.config.path)/$(params.CONFIGMAP_PREFIX)_UPDATE_FLAG_PATH)"
      echo "$(params.CONFIGMAP_PREFIX)_UPDATE_FLAG_PATH) : $UPDATE_FLAG_PATH"
      yq "$UPDATE_FLAG_PATH = true" $VALUES_PATH > $VALUES_PATH.tmp
      mv $VALUES_PATH.tmp $VALUES_PATH
      yq "$YAML_PATH = '$TAG_VALUE'" $VALUES_PATH > $VALUES_PATH.tmp
      mv $VALUES_PATH.tmp $VALUES_PATH
    workingDir: $(workspaces.gitrepos.path)/$(params.subdirectory)
