kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: mock
spec:
  params:
  - name: MESSAGE
    type: string
    description: |
      The message to echo.
    default: "Hello from mock-task"
  steps:
  - image: registry.redhat.io/ubi9-minimal:9.5
    script: |
      #!/bin/bash
      echo "$(params.MESSAGE)"
