apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tkn
spec:
  params:
  - name: tkn-image
    description: tkn CLI container image to run this task
    default: registry.redhat.io/openshift-pipelines/pipelines-cli-tkn-rhel8:v1.16.1-2
  - name: ARGS
    type: array
    description: tkn CLI arguments to run
  steps:
    - name: tkn
      image: "$(params.tkn-image)"
      command: ["/usr/bin/tkn"]
      args: ["$(params.ARGS)"]