{{ $ns := printf "%s-%s" $.Values.global.pattern  $.Values.clusterGroup.name }}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-secret-ie-namespaced-argocd
  namespace: {{ $ns }}
spec:
  data:
    - conversionStrategy: None
      match:
        remoteRef:
          remoteKey: pushsecrets/namespaced-argo
          property: password
        secretKey: admin.password
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: vault-backend
  selector:
    secret:
      name: {{ $.Values.clusterGroup.name }}-gitops-cluster
  updatePolicy: Replace
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: external-secret-ie-namespaced-argocd
  namespace: manuela-ci
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: argocd-env
    template:
      type: Opaque
      engineVersion: v2
      metadata:
      data:
        ARGOCD_USERNAME: admin
        ARGOCD_PASSWORD: "{{ `{{ .argo_admin_password }}` }}"
  data:
  - secretKey: argo_admin_password
    remoteRef:
      key: "pushsecrets/namespaced-argo"
      property: "password"
