# The push secret fetches the randomly generated gitea-admin-secret username+password to vault
# The External Secret will fetch those credentials from vault and place them in the gitea-admin-external-secret
# in the manuela-ci namespace
{{- $giturl := coalesce .Values.global.git.hostname (printf "gitea-route-vp-gitea.%s" .Values.global.localClusterDomain) }}
{{- $full_giturl := printf "https://%s/%s/" $giturl .Values.global.git.account }}

{{- if .Values.clusterGroup.isHubCluster }}
{{- if .Values.global.originURL }}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-secret-gitea-admin
  namespace: vp-gitea
spec:
  data:
    - conversionStrategy: None
      match:
        remoteRef:
          remoteKey: pushsecrets/gitea_admin
          property: username
        secretKey: username
    - conversionStrategy: None
      match:
        remoteRef:
          remoteKey: pushsecrets/gitea_admin
          property: password
        secretKey: password
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: vault-backend
  selector:
    secret:
      name: gitea-admin-secret
  updatePolicy: Replace
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: gitea-admin-external-secret
  namespace: manuela-ci
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: gitea-admin-secret
    template:
      metadata:
        annotations:
          # Tekton magic, see https://tekton.dev/vault/pipelines-v0.15.2/auth/
          tekton.dev/git-0: {{ $full_giturl }}
      type: kubernetes.io/basic-auth
      engineVersion: v2
      data:
        username: "{{ `{{ .gitea_admin_user }}` }}"
        password: "{{ `{{ .gitea_admin_password }}` }}"
  data:
  - secretKey: gitea_admin_user
    remoteRef:
      key: "pushsecrets/gitea_admin"
      property: "username"

  - secretKey: gitea_admin_password
    remoteRef:
      key: "pushsecrets/gitea_admin"
      property: "password"
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: gitea-admin-external-secret
  namespace: ml-development
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: gitea-admin-secret-and-branch
    template:
      metadata:
        annotations:
          # Tekton magic, see https://tekton.dev/vault/pipelines-v0.15.2/auth/
          tekton.dev/git-0: {{ $full_giturl }}
      type: Opaque
      engineVersion: v2
      data:
        username: "{{ `{{ .gitea_admin_user }}` }}"
        password: "{{ `{{ .gitea_admin_password }}` }}"
        branch: {{ $.Values.global.targetRevision }}
  data:
  - secretKey: gitea_admin_user
    remoteRef:
      key: "pushsecrets/gitea_admin"
      property: "username"

  - secretKey: gitea_admin_password
    remoteRef:
      key: "pushsecrets/gitea_admin"
      property: "password"
{{- end }}
{{- end }}
