---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: messaging-secret
  namespace: manuela-stormshift-messaging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: messaging-secret
    template:
      type: Opaque
      engineVersion: v2
      data:
        MQTT_PASSWORD: "{{ `{{ .iotuser_password }}` }}"
  data:
  - secretKey: iotuser_password
    remoteRef:
      key: "pushsecrets/iotsecrets"
      property: "password"
