apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
  namespace: manuela-stormshift-messaging
spec:
  lookupPolicy:
    local: true
  tags:
  - name: 0.3.2-18
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-consumer:0.3.2-18
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-19
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-consumer:0.3.2-19
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-20
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-consumer:0.3.2-20
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-21
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-consumer:0.3.2-21
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-9
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-consumer:0.3.2-9
    importPolicy: {}
    referencePolicy:
      type: Local
