apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
  namespace: manuela-stormshift-messaging
spec:
  lookupPolicy:
    local: true
  tags:
  - name: 0.3.2-211
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-consumer:0.3.2-211
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-212
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-consumer:0.3.2-212
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-213
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-consumer:0.3.2-213
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-214
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-consumer:0.3.2-214
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.2-215
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-consumer:0.3.2-215
    importPolicy: {}
    referencePolicy:
      type: Local
