global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  git:
    provider: github.com
    account: mhjacks
    username: mhjacks
    email: mhjacks@redhat.com
    dev_revision: main

  quay:
    provider: quay.io
    account: martjack

  datacenter:
    clustername: mhjacks-dc20
    domain: blueprints.rhecoeng.com

  edge:
    clustername: mhjacks-f20
    domain: blueprints.rhecoeng.com

