clusterGroup:
  name: factory
  isHubCluster: false

  namespaces:
  - manuela-stormshift-line-dashboard
  - manuela-stormshift-machine-sensor
  - manuela-stormshift-messaging

  subscriptions:
  - name: seldon-operator
    namespace: manuela-stormshift-messaging
    source: community-operators

  - name: amq-streams
    namespace: manuela-stormshift-messaging

  - name: amq-broker-rhel8
    namespace: manuela-stormshift-messaging

  - name: red-hat-camel-k
    namespace: manuela-stormshift-messaging

  projects:
  - factory

  argoCD:
    configManagementPlugins:
      - name: helm-with-kustomize
        image: quay.io/argoproj/argocd:latest
        pluginConfig: |
          apiVersion: argoproj.io/v1alpha1
          kind: ConfigManagementPlugin
          metadata:
            name: helm-with-kustomize
          spec:
            preserveFileMode: true
            parameters:
              preserveFileMode: true
            init:
              command: ["/bin/sh", "-c"]
              args: ["helm dependency build"]
            generate:
              command: ["/bin/bash", "-c"]
              args: ["helm template . --name-template ${ARGOCD_APP_NAME:0:52}
                  -f $(git rev-parse --show-toplevel)/values-global.yaml
                  -f $(git rev-parse --show-toplevel)/values-{{ .Values.clusterGroup.name }}.yaml
                  --set global.repoURL=$ARGOCD_APP_SOURCE_REPO_URL
                  --set global.targetRevision=$ARGOCD_APP_SOURCE_TARGET_REVISION
                  --set global.namespace=$ARGOCD_APP_NAMESPACE
                  --set global.pattern={{ .Values.global.pattern }}
                  --set global.clusterDomain={{ .Values.global.clusterDomain }}
                  --set global.hubClusterDomain={{ .Values.global.hubClusterDomain }}
                  --set global.localClusterDomain={{ coalesce .Values.global.localClusterDomain .Values.global.hubClusterDomain }}
                  --set clusterGroup.name={{ .Values.clusterGroup.name }}
                  --post-renderer ./kustomize"]

  applications:
  - name: stormshift
    project: factory
    path: charts/factory/manuela-stormshift
    plugin:
      name: helm-with-kustomize

#
#  To have apps in multiple flavors, use namespaces and use helm overrides as appropriate
#
#  - name: pipelines
#    namespace: production
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: stable
#    overrides:
#    - name: myparam
#      value: myparam
#
#  - name: pipelines
#    namespace: staging
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: main
#
#   Additional applications
#   Be sure to include additional resources your apps will require
#   +X machines
#   +Y RAM
#   +Z CPU
#  - name: vendor-app
#    namespace: default
#    project: vendor
#    path: path/to/myapp
#    repoURL: https://github.com/vendor/applications.git
#    targetRevision: main
