main:
  clusterGroupName: datacenter

global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  imageregistry:
    account: martjack
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: mhjacks
    username: mhjacks
    email: mhjacks@redhat.com
    dev_revision: main
