main:
  clusterGroupName: datacenter

global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  imageregistry:
    account: martjack
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: mhjacks
    username: mhjacks
    email: mhjacks@swbell.net
    dev_revision: main

  s3:
    bucket:
      name: mhjacks-bucket
      region: us-west-1
      message:
        aggregation:
          count: 50
      custom:
        endpoint:
          enabled: false
