apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: seed-iot-software-sensor-run
spec:
  pipelineRef:
    name: seed-iot-software-sensor
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - configMap:
      name: environment
    name: config
  - name: argocd-env-secret
    secret:
      secretName: argocd-env
  - name: build-artifacts
    # persistentVolumeClaim:
    #   claimName: build-artifacts-rwo
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: gitrepos
    # persistentVolumeClaim:
    #   claimName: iot-software-sensor-rwo
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 128Mi
