apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: seed-run-
  namespace: manuela-ci
  labels:
    argocd.argoproj.io/instance: pipelines-industrial-edge-datacenter
    tekton.dev/pipeline: seed
spec:
  pipelineRef:
    name: seed
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - configMap:
      name: environment
    name: config
  - name: gitrepos
    persistentVolumeClaim:
      claimName: gitrepos-rwo
  - name: build-artifacts
    persistentVolumeClaim:
      claimName: build-artifacts-rwo
