apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: stage-production-run-
  namespace: manuela-ci
  labels:
    argocd.argoproj.io/instance: pipelines-industrial-edge-datacenter
    tekton.dev/pipeline: stage-production
spec:
  pipelineRef:
    name: stage-production
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: gitrepos
      persistentVolumeClaim:
        claimName: gitrepos-rwo
    - configMap:
        name: environment
      name: config
    - name: argocd-env-secret
      secret:
        secretName: argocd-env
    - name: github-secret
      secret:
        secretName: git-repo-credentials
    - name: build-artifacts
      persistentVolumeClaim:
        claimName: build-artifacts-rwo
#  For testing purposes adjust the below values and uncomment
#  params:
#    - name: TAG
#      value: 0.3.2-18
#    - name: CONFIGMAP_PREFIX
#      value: IOT_CONSUMER
#    - name: SOURCE_IMAGE
#      value: image-registry.openshift-image-registry.svc:5000/manuela-tst-all/messaging
#    - name: COMPONENT_NAME
#      value: iot_consumer
