# This generates a random secret that will be securely pushed to vault and then 
# pulled out from vault to all messaging and machine sensor pods
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: iotuser-password
spec:
  length: 20
  digits: 5
  symbols: 5
  symbolCharacters: "-_$@"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: iotuser-password
spec:
  refreshInterval: 0m
  target:
    name: iotuser-password
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: iotuser-password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-secret-iot-password
spec:
  data:
    - conversionStrategy: None
      match:
        remoteRef:
          remoteKey: pushsecrets/iotsecrets
          property: password
        secretKey: password
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: vault-backend
  selector:
    secret:
      name: iotuser-password
  updatePolicy: Replace
---
