kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-name: "Industrial edge workbench"
    opendatahub.io/notebook-image-desc: "Workbench for the industrial edge pattern"
  name: industrial-edge
  namespace: redhat-ods-applications
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
    opendatahub.io/notebook-image: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: industrial-edge-v0.1.0
      annotations:
        opendatahub.io/notebook-python-dependencies: '[]'
        opendatahub.io/notebook-software: '[]'
        # Once we we merge the integrate_rhoai branch in manuela-dev into main
        # we can change the image here and point it to latest and/or use a vX.Y.Z tag
        openshift.io/imported-from: 'quay.io/hybridcloudpatterns/manuela-workbench:integrate_rhoai'
      from:
        kind: DockerImage
        name: 'quay.io/hybridcloudpatterns/manuela-workbench:integrate_rhoai'
      generation: 2
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-desc: Open Data Hub Tools & Extensions Companion
    opendatahub.io/notebook-image-name: ODH TEC
    opendatahub.io/notebook-image-url: 'quay.io/rh-aiservices-bu/odh-tec:latest'
  name: odh-tec
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/created-by: byon
    opendatahub.io/dashboard: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: v0.1
      annotations:
        opendatahub.io/notebook-python-dependencies: ''
        opendatahub.io/notebook-software: ''
        openshift.io/imported-from: 'quay.io/rh-aiservices-bu/odh-tec:latest'
      from:
        kind: DockerImage
        name: 'quay.io/rh-aiservices-bu/odh-tec:latest'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
