global:
  datacenter:
    clustername: datacenter-XXXXX
    domain: BASEDOMAIN

clusterGroup:
  name: datacenter
  isHubCluster: true
  managedClusterGroups:
    factory:
      name: factory
      # repoURL: https://github.com/dagger-refuse-cool/manuela-factory.git
      # targetRevision: main
      helmOverrides:
      # Values must be strings!
      - name: clusterGroup.isHubCluster
        value: "false"
      clusterSelector:
#        matchLabels:
#          clusterGroup: factory
        matchExpressions:
        - key: vendor
          operator: In
          values:
            - OpenShift

kafka:
  s3:
    bucket: anomaly-detection
    endpointurl: http://s3.openshift-storage.svc
    message:
      aggregation:
        count: 50
  broker:
    uri: "prod-kafka-cluster-kafka-bootstrap.manuela-data-lake.svc:9092"
    topic:
      temperature: "factory-kafka-cluster.manuela-factory.iot-sensor-sw-temperature"
      vibration: "factory-kafka-cluster.manuela-factory.iot-sensor-sw-vibration"

secretStore:
  name: vault-backend
  kind: ClusterSecretStore
