apiVersion: v1
kind: ConfigMap
metadata:
  name: messaging-configmap
data:
  VIBRATION_ALERT_ENABLED: "{{ .Values.messaging.vibrationAlert }}"
  VIBRATION_ANOMALY_ENABLED: "{{ .Values.messaging.vibrationAnomaly }}"
  NODE_TLS_REJECT_UNAUTHORIZED: "{{ .Values.messaging.nodeTlsReject }}"
  MQTT_BROKER: "ws://broker-amq-mqtt-all-0-svc:61616"
  MQTT_USER: "iotuser"
  PORT: "3000"
  SOCKET_PATH: "/api/service-web/socket"
  TEMPERATURE_THRESHOLD: "70.0"
  TEMPERATURE_ALERT_ENABLED: "true"
  TOPIC_GPS: "iot-sensor/sw/gps"
  TOPIC_TEMPERATURE: "iot-sensor/sw/temperature"
  TOPIC_VIBRATION: "iot-sensor/sw/vibration"
  TOPIC_LIGHT: "iot-sensor/sw/light"
  ANOMALY_DETECTION_URL: "http://modelmesh-serving.manuela-tst-all:8008"
  ANOMALY_DETECTION_URL_PATH: "/v2/models/inference-service/infer"
