apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: machine-sensor
  namespace: manuela-stormshift-machine-sensor
spec:
  lookupPolicy:
    local: true
  tags:
  - name: 0.3.1-139
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-software-sensor:0.3.1-139
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-140
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-software-sensor:0.3.1-140
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-141
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-software-sensor:0.3.1-141
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-142
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-software-sensor:0.3.1-142
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.3.1-143
    from:
      kind: DockerImage
      name: quay.io/martjack/iot-software-sensor:0.3.1-143
    importPolicy: {}
    referencePolicy:
      type: Local
