{{- if len $.Values.clusterGroup.argoCD.configManagementPlugins }}
{{- range $cmp := $.Values.clusterGroup.argoCD.configManagementPlugins }}
{{- if $cmp.pluginConfig }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: "argocd-cmp-{{ $cmp.name }}"
  namespace: {{ $.Values.global.pattern }}-{{ $.Values.clusterGroup.name }}
data:
  {{ $cmp.pluginConfig | indent 2 }}
{{- end }}
{{- end }}
{{- end }}
