{{- if and .Values.clusterGroup .Values.clusterGroup.isHubCluster }}
{{- if .Values.global.originURL }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: s3-anomaly-external-secret
  namespace: manuela-tst-all
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: s3-anomaly
    template:
      type: Opaque
      engineVersion: v2
      data:
        application.properties: |
          AWS_SECRET_ACCESS_KEY: {{ `{{ .aws_secret_access_key }}` }}
          AWS_ACCESS_KEY_ID: {{ `{{ .aws_access_key_id }}` }}
  data:
  - secretKey: aws_secret_access_key
    remoteRef:
      key: "pushsecrets/s3-anomaly"
      property: "AWS_SECRET_ACCESS_KEY"

  - secretKey: aws_access_key_id
    remoteRef:
      key: "pushsecrets/s3-anomaly"
      property: "AWS_ACCESS_KEY_ID"
{{- end }}
{{- end }}

