apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-base-images
spec:
  workspaces:
  - name: gitrepos
  - name: config
  params:
  - name: PATH_CONTEXT
    type: string
    default: tekton/images/httpd-ionic
  - name: OUTPUT_IMAGE_PROVIDER_CONFIGMAPKEY
    type: string
    default: IMAGE_PROVIDER
  - name: OUTPUT_IMAGE_ACCOUNT_CONFIGMAPKEY
    type: string
    default: IMAGE_ACCOUNT
  - name: OUTPUT_IMAGE_NAME
    type: string
    default: httpd-ionic
  - name: DEV_REVISION
    type: string
    default: main
  tasks:
  - name: git-clone-dev
    taskRef:
      name: git-clone-with-tags
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: config
      workspace: config
    params:
    - name: url_configmapkey
      value: GIT_DEV_REPO_URL
    - name: revision
      value: $(params.DEV_REVISION)
    - name: subdirectory
      value: dev
    - name: deleteExisting
      value: "true"

  - name: buildah-build
    taskRef:
      name: buildah
    runAfter:
    - git-clone-dev
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: config
      workspace: config
    params:
    - name: TLSVERIFY
      value: "false"
    - name: PATH_CONTEXT
      value: $(params.PATH_CONTEXT)
    - name: TAG
      value: latest
    - name: OUTPUT_IMAGE_PROVIDER_CONFIGMAPKEY
      value: $(params.OUTPUT_IMAGE_PROVIDER_CONFIGMAPKEY)
    - name: OUTPUT_IMAGE_ACCOUNT_CONFIGMAPKEY
      value: $(params.OUTPUT_IMAGE_ACCOUNT_CONFIGMAPKEY)
    - name: OUTPUT_IMAGE_NAME
      value: $(params.OUTPUT_IMAGE_NAME)
