apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: iot-component
spec:
  workspaces:
  - name: gitrepos
  - name: config
  - name: build-artifacts
  params:
  - name: component_name
    type: string
    description: Name of IoT component to build
  - name: seed_prod_with_tags
    type: string
    description: Seed tags to prod env
    default: 'false'
  - name: builder_image
    type: string
    description: The builder image to use for building the component
  - name: chained_build_dockerfile
    type: string
    description: If a chained build is to be executed, the second part of the DOCKERFILE
    default: ""
  - name: output_image_name
    type: string
    description: Name of the output image after build
  - name: target_image_configmapkey
    type: string
    description: Name of key of the target image in the configmap
  - name: configmap_prefix
    type: string
    description: The prefix of the key in the configmap for the component
  tasks:
  - name: git-clone-dev
    taskRef:
      name: git-clone-with-tags
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: config
      workspace: config
    params:
    - name: url_configmapkey
      value: GIT_DEV_REPO_URL
    - name: revision
      value: {{ .Values.global.git.dev_revision }}
    - name: subdirectory
      value: dev
    - name: deleteExisting
      value: "true"

  - name: git-clone-ops
    taskRef:
      name: git-clone-with-tags
    runAfter:
    - git-clone-dev
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: config
      workspace: config
    params:
    - name: url_configmapkey
      value: GIT_OPS_REPO_TEST_URL
    - name: revision
      value: {{ .Values.global.targetRevision }}
    - name: subdirectory
      value: ops
    - name: deleteExisting
      value: "true"

  - name: bump-build-version-iot-component
    displayName: "Bump version for $(params.component_name)"
    taskRef:
      name: bumpversion
    runAfter:
    - git-clone-ops
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    params:
    - name: component_name
      value: $(params.component_name)
    - name: version_file_path
      value: components/$(params.component_name)/VERSION

  - name: s2i-build-iot-component
    displayName: "S2I build IoT $(params.component_name)"
    taskRef:
      name: s2i
    runAfter:
    - bump-build-version-iot-component
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: build-artifacts
      workspace: build-artifacts
    params:
    - name: TLSVERIFY
      value: "false"
    - name: PATH_CONTEXT
      value: components/$(params.component_name)
    - name: BUILDER_IMAGE
      value: $(params.builder_image)
    - name: CHAINED_BUILD_DOCKERFILE
      value: $(params.chained_build_dockerfile)
    - name: TAG
      value: $(tasks.bump-build-version-iot-component.results.image-tag)
    - name: OUTPUT_IMAGE
      value: image-registry.openshift-image-registry.svc:5000/manuela-tst-all/$(params.output_image_name)

  - name: copy-image-to-remote-registry
    displayName: "Copy image to remote registry"
    taskRef:
      name: skopeo-copy
    runAfter:
    - s2i-build-iot-component
    workspaces:
    - name: config
      workspace: config
    params:
    - name: TAG
      value: $(tasks.bump-build-version-iot-component.results.image-tag)
    - name: SOURCE_IMAGE
      value: image-registry.openshift-image-registry.svc:5000/manuela-tst-all/$(params.output_image_name)
    - name: TARGET_IMAGE_CONFIGMAPKEY
      value: $(params.target_image_configmapkey)

  - name: push-dev-tag
    taskRef:
      name: github-push
    runAfter:
    - copy-image-to-remote-registry
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    params:
    - name: PUSH_FLAGS
      value: --tags


  - name: modify-ops-test-iot-component
    taskRef:
      name: gitops-imagetag
    runAfter:
    - push-dev-tag
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: config
      workspace: config
    params:
    - name: CONFIGMAP_PREFIX
      value: $(params.configmap_prefix)
    - name: ENVIRONMENT
      value: TEST
    - name: TAG
      value: $(tasks.bump-build-version-iot-component.results.image-tag)
    - name: subdirectory
      value: ops

  - name: modify-ops-prod-iot-component
    when:
      - input: "$(params.seed_prod_with_tags)"
        operator: in
        values: ["true"]
    taskRef:
      name: gitops-imagetag
    runAfter:
    - modify-ops-test-iot-component
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: config
      workspace: config
    params:
    - name: CONFIGMAP_PREFIX
      value: $(params.configmap_prefix)
    - name: ENVIRONMENT
      value: PROD
    - name: TAG
      value: $(tasks.bump-build-version-iot-component.results.image-tag)
    - name: subdirectory
      value: ops

  - name: commit-ops
    taskRef:
      name: git-commit
    runAfter:
    - modify-ops-prod-iot-component
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    - name: config
      workspace: config
    params:
    - name: subdirectory
      value: ops

  - name: push-ops
    taskRef:
      name: github-push
    runAfter:
    - commit-ops
    workspaces:
    - name: gitrepos
      workspace: gitrepos
    params:
    - name: subdirectory
      value: ops
    - name: PUSH_FLAGS
      value: --all
