apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: seed
spec:
  workspaces:
  - name: gitrepos
  - name: config
  - name: build-artifacts
  params:
  - name: DEV_REVISION
    type: string
    default: {{ .Values.global.git.dev_revision }}
  - name: OPS_REVISION
    type: string
    default: {{ .Values.global.targetRevision }}
  tasks:
  - name: build-base-images
    taskRef:
      name: tkn
      kind: Task
    params:
    - name: ARGS
      value:
      - pipeline
      - start
      - build-base-images
      - --param
      - PATH_CONTEXT=tekton/images/httpd-ionic
      - --param
      - OUTPUT_IMAGE_PROVIDER_CONFIGMAPKEY=IMAGE_PROVIDER
      - --param
      - OUTPUT_IMAGE_ACCOUNT_CONFIGMAPKEY=IMAGE_ACCOUNT
      - --param
      - OUTPUT_IMAGE_NAME=http-ionic
      - --param
      - DEV_REVISION=$(params.DEV_REVISION)
      - --workspace
      - name=gitrepos,claimName=gitrepos-rwo
      - --workspace
      - name=config,config=environment
      - --workspace
      - name=build-artifacts,claimName=build-artifacts-rwo
      - --showlog
      - --nocolour

  - name: seed-iot-anomaly-detection
    runAfter:
      - build-base-images
    taskRef:
      name: tkn
      kind: Task
    params:
    - name: ARGS
      value:
      - pipeline
      - start
      - seed-iot-anomaly-detection
      - --workspace
      - name=gitrepos,claimName=gitrepos-rwo
      - --workspace
      - name=config,config=environment
      - --workspace
      - name=build-artifacts,claimName=build-artifacts-rwo
      - --showlog
      - --nocolour

  - name: seed-iot-consumer
    runAfter:
      - seed-iot-anomaly-detection
    taskRef:
      name: tkn
      kind: Task
    params:
    - name: ARGS
      value:
      - pipeline
      - start
      - seed-iot-consumer
      - --workspace
      - name=gitrepos,claimName=gitrepos-rwo
      - --workspace
      - name=config,config=environment
      - --workspace
      - name=build-artifacts,claimName=build-artifacts-rwo
      - --showlog
      - --nocolour

  - name: seed-iot-frontend
    runAfter:
      - seed-iot-consumer
    taskRef:
      name: tkn
      kind: Task
    params:
    - name: ARGS
      value:
      - pipeline
      - start
      - seed-iot-frontend
      - --workspace
      - name=gitrepos,claimName=gitrepos-rwo
      - --workspace
      - name=config,config=environment
      - --workspace
      - name=build-artifacts,claimName=build-artifacts-rwo
      - --showlog
      - --nocolour

  - name: seed-iot-software-sensor
    runAfter:
      - seed-iot-frontend
    taskRef:
      name: tkn
      kind: Task
    params:
    - name: ARGS
      value:
      - pipeline
      - start
      - seed-iot-software-sensor
      - --workspace
      - name=gitrepos,claimName=gitrepos-rwo
      - --workspace
      - name=config,config=environment
      - --workspace
      - name=build-artifacts,claimName=build-artifacts-rwo
      - --showlog
      - --nocolour
