apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: seed
spec:
  workspaces:
  - name: gitrepos
  - name: config
  - name: build-artifacts
  params:
  - name: DEV_REVISION
    type: string
    default: {{ .Values.global.git.dev_revision }}
  - name: OPS_REVISION
    type: string
    default: {{ .Values.global.targetRevision }}
  tasks:
  - name: build-base-images
    taskRef:
      name: tkn
      kind: Task
    params:
    - name: ARGS
      value:
      - pipeline
      - start
      - build-base-images
      - --param
      - PATH_CONTEXT=tekton/images/httpd-ionic
      - --param
      - OUTPUT_IMAGE_PROVIDER_CONFIGMAPKEY=IMAGE_PROVIDER
      - --param
      - OUTPUT_IMAGE_ACCOUNT_CONFIGMAPKEY=IMAGE_ACCOUNT
      - --param
      - OUTPUT_IMAGE_NAME=httpd-ionic
      - --param
      - DEV_REVISION=$(params.DEV_REVISION)
      - --workspace
      - name=gitrepos,claimName=gitrepos-rwo
      - --workspace
      - name=config,config=environment
      - --workspace
      - name=build-artifacts,claimName=build-artifacts-rwo
      - --showlog
      - --nocolour

  - name: seed-iot-anomaly-detection
    runAfter:
      - build-base-images
    taskRef:
      name: tkn
      kind: Task
    params:
    - name: ARGS
      value:
      - pipeline
      - start
      - iot-component
      - --param
      - component_name=iot-anomaly-detection
      - --param
      - seed_prod_with_tags=true
      - --param
      - builder_image=quay.io/hybridcloudpatterns/python-38-rhel7
      - --param
      - chained_build_dockerfile=""
      - --param
      - output_image_name=anomaly-detection
      - --param
      - target_image_configmapkey=IOT_ANOMALY_IMAGE
      - --param
      - configmap_prefix=IOT_ANOMALY
      - --workspace
      - name=gitrepos,claimName=gitrepos-rwo
      - --workspace
      - name=config,config=environment
      - --workspace
      - name=build-artifacts,claimName=build-artifacts-rwo
      - --prefix-name
      - seed-iot-anomaly-detection
      - --showlog
      - --nocolour
      - --exit-with-pipelinerun-error

  - name: seed-iot-consumer
    runAfter:
      - seed-iot-anomaly-detection
    taskRef:
      name: tkn
      kind: Task
    params:
    - name: ARGS
      value:
      - pipeline
      - start
      - iot-component
      - --param
      - component_name=iot-consumer
      - --param
      - seed_prod_with_tags=true
      - --param
      - builder_image=registry.access.redhat.com/rhscl/nodejs-10-rhel7
      - --param
      - chained_build_dockerfile=""
      - --param
      - output_image_name=messaging
      - --param
      - target_image_configmapkey=IOT_CONSUMER_IMAGE
      - --param
      - configmap_prefix=IOT_CONSUMER
      - --workspace
      - name=gitrepos,claimName=gitrepos-rwo
      - --workspace
      - name=config,config=environment
      - --workspace
      - name=build-artifacts,claimName=build-artifacts-rwo
      - --prefix-name
      - seed-iot-consumer
      - --showlog
      - --nocolour
      - --exit-with-pipelinerun-error

  - name: seed-iot-frontend
    runAfter:
      - seed-iot-consumer
    taskRef:
      name: tkn
      kind: Task
    params:
    - name: ARGS
      value:
      - pipeline
      - start
      - iot-component
      - --param
      - component_name=iot-frontend
      - --param
      - seed_prod_with_tags=true
      - --param
      - builder_image=quay.io/hybridcloudpatterns/ubi8-s2i-web-app
      - --param
      - chained_build_dockerfile=FROM quay.io/hybridcloudpatterns/httpd-ionic\nCOPY --from=0 /opt/app-root/output /var/www/html/
      - --param
      - output_image_name=line-dashboard
      - --param
      - target_image_configmapkey=IOT_FRONTEND_IMAGE
      - --param
      - configmap_prefix=IOT_FRONTEND
      - --workspace
      - name=gitrepos,claimName=gitrepos-rwo
      - --workspace
      - name=config,config=environment
      - --workspace
      - name=build-artifacts,claimName=build-artifacts-rwo
      - --prefix-name
      - seed-iot-frontend
      - --showlog
      - --nocolour
      - --exit-with-pipelinerun-error

  - name: seed-iot-software-sensor
    runAfter:
      - seed-iot-frontend
    taskRef:
      name: tkn
      kind: Task
    params:
    - name: ARGS
      value:
      - pipeline
      - start
      - iot-component
      - --param
      - component_name=iot-software-sensor
      - --param
      - seed_prod_with_tags=true
      - --param
      - builder_image=registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
      - --param
      - chained_build_dockerfile=""
      - --param
      - output_image_name=machine-sensor
      - --param
      - target_image_configmapkey=IOT_SWSENSOR_IMAGE
      - --param
      - configmap_prefix=IOT_SWSENSOR
      - --workspace
      - name=gitrepos,claimName=gitrepos-rwo
      - --workspace
      - name=config,config=environment
      - --workspace
      - name=build-artifacts,claimName=build-artifacts-rwo
      - --prefix-name
      - seed-iot-software-sensor
      - --showlog
      - --nocolour
      - --exit-with-pipelinerun-error
