---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: s3-hub-bucket
  namespace: manuela-inference
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: aws-connection-user-bucket
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels:
          opendatahub.io/dashboard: "true"
          opendatahub.io/managed: "true"
        annotations:
          opendatahub.io/connection-type: s3
      # FIXME(bandini|akos): For now we use the http endpoint on the hub because trusting the
      # hub CA is not working for us now
      data:
        AWS_SECRET_ACCESS_KEY: "{{ `{{ .aws_secret_access_key }}` }}"
        AWS_ACCESS_KEY_ID: "{{ `{{ .aws_access_key_id }}` }}"
        AWS_S3_BUCKET: user-bucket
        AWS_S3_ENDPOINT: {{ printf "http://s3-openshift-storage.%s" .Values.global.hubClusterDomain }}
        AWS_DEFAULT_REGION: {{ $.Values.s3.default_region }}
  data:
  - secretKey: aws_secret_access_key
    remoteRef:
      key: "pushsecrets/user-bucket"
      property: "AWS_SECRET_ACCESS_KEY"

  - secretKey: aws_access_key_id
    remoteRef:
      key: "pushsecrets/user-bucket"
      property: "AWS_ACCESS_KEY_ID"

