{{- if .Values.main.options.bootstrap }}
kind: Secret
apiVersion: v1
metadata:
  name: github
  namespace: manuela-ci
type: Opaque
data:
  # Go to: https://github.com/settings/tokens
  # Then: echo -n 'your string value' | base64
  token: {{ .Values.secrets.git.authToken }}
  user: {{ .Values.secrets.git.accountToken }}
{{- end }}