apiVersion: v1
kind: Namespace
metadata:
  name: manuela-ci
  labels:
    manuela-role: pipeline
    app.kubernetes.io/instance: manuela
      #argocd.argoproj.io/managed-by: openshift-gitops
spec:
  finalizers:
  - kubernetes
