---
apiVersion: v1
kind: Secret
metadata:
  name: git-repo-credentials
  namespace: manuela-ci
  annotations:
    # Tekton magic, see https://tekton.dev/vault/pipelines-v0.15.2/auth/
    tekton.dev/git-0: https://{{ .Values.global.git.hostname }}/{{ .Values.global.git.account }}
type: kubernetes.io/basic-auth
stringData:
# These elements will be base64-encoded by kubernetes once added, so enter them in plaintext
  username: {{ .Values.secrets.git.username }}
  password: {{ .Values.secrets.git.password }}
