---
apiVersion: v1
kind: ServiceAccount
metadata:
# pipeline is configured in the openshift-pipelines namespace as the default serviceaccount for pipelineruns
# So let's use that as our primary serviceaccount
# To change this setting, edit the configmap config-defaults in ns openshift-pipelines
  name: pipeline
  namespace: manuela-ci
secrets:
- name: git-repo-credentials
{{-   if eq .Values.global.imageregistry.type "quay" }}
- name: image-registry-credentials
{{-   end }}
