{{- if .Values.main.options.bootstrap }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  namespace: manuela-ci
secrets:
- name: git-repo-credentials
{{-   if eq .Values.global.imageregistry.type "quay" }}
- name: image-registry-credentials
{{-   end }}
{{- end }}
