global:
  datacenter:
    clustername: datacenter-XXXXX
    domain: BASEDOMAIN
  s3:
    bucket:
      name: BUCKETNAME
      region: AWSREGION
      message:
        aggregation:
          count: 50
      custom:
        endpoint:
          enabled: false

messaging:
  vibrationAlert: true
  vibrationAnomaly: true
  nodeTlsReject: 0

machineSensor1:
  port: 80

machineSensor2:
  port: 80
  sensorTemperature: false

mqtt:
  broker:
    uri: "tcp://broker-amq-mqtt-all-0-svc.manuela-tst-all.svc:61616"
    clientId: "MQTT2KafkaRouteDev"
    topic:
      temperature: "iot-sensor/sw/temperature"
      vibration: "iot-sensor/sw/vibration"

kafka:
  broker:
    uri: "dev-kafka-cluster-kafka-bootstrap.manuela-tst-all.svc:9092"
    topic:
      temperature: "iot-sensor-sw-temperature"
      vibration: "iot-sensor-sw-vibration"

subscriptions:
  version:
    installPlanApproval: Automatic
    seldon: v1.13.1

machine_sensor:
  updated_images: false
  bootstrap_image: quay.io/hybridcloudpatterns/iot-software-sensor:0.3.1
  bootstrap_tag: 0.3.1
  image_location: image-registry.openshift-image-registry.svc:5000/manuela-tst-all/machine-sensor
  repo_name: iot-software-sensor
  tag: 0.3.1

iot_anomaly_detection:
  updated_images: false
  bootstrap_image: quay.io/hybridcloudpatterns/iot-anomaly-detection:0.3.2
  bootstrap_tag: 0.3.2
  image_location: image-registry.openshift-image-registry.svc:5000/manuela-tst-all/anomaly-detection
  repo_name: iot-anomaly-detection
  tag: 0.3.2

iot_consumer:
  updated_images: false
  bootstrap_image: quay.io/hybridcloudpatterns/iot-consumer:0.3.2
  bootstrap_tag: 0.3.2
  image_location: image-registry.openshift-image-registry.svc:5000/manuela-tst-all/messaging
  repo_name: iot-consumer
  tag: 0.3.2

iot_frontend:
  updated_images: false
  bootstrap_image: quay.io/hybridcloudpatterns/iot-frontend:0.3.1
  bootstrap_tag: 0.3.1
  image_location: image-registry.openshift-image-registry.svc:5000/manuela-tst-all/line-dashboard
  repo_name: iot-frontend
  tag: 0.3.1
