apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: build-image-httpd-ionic
objects:
- apiVersion: tekton.dev/v1beta1
  kind: PipelineRun
  metadata:
    generateName: build-image-httpd-ionic-
  spec:
    pipelineRef:
      name: build-images
    workspaces:
    - name: config
      configMap:
        name: environment
    - name: gitrepos
      volumeClaimTemplate:
        spec:
          accessModes: 
          - ReadWriteMany
          resources:
            requests:
              storage: 128Gi
      # persistentVolumeClaim:
      #   claimName: build-images
    params:
    - name: PATH_CONTEXT
      value: tekton/images/httpd-ionic
    - name: OUTPUT_IMAGE_PROVIDER_CONFIGMAPKEY
      value: IMAGE_PROVIDER
    - name: OUTPUT_IMAGE_ACCOUNT_CONFIGMAPKEY
      value: IMAGE_ACCOUNT
    - name: OUTPUT_IMAGE_NAME
      value: httpd-ionic
