global:
  git:
    hostname: github.com
    account: PLAINTEXT
    username: PLAINTEXT
    email: SOMEWHERE@EXAMPLE.COM
    dev_revision: main

  imageregistry:
    account: PLAINTEXT
    hostname: quay.io
    type: quay

  datacenter:
    clustername: datacenter-XXXXX
    domain: BASEDOMAIN

  edge:
    clustername: edge-XXXXX
    domain: BASEDOMAIN

  s3:
    bucket:
      name: manuela-data-lake
      region: us-west-1
      message:
        aggregation:
          count: 10
      custom:
        endpoint:
          enabled: true


messaging:
  vibrationAlert: true
  vibrationAnomaly: true
  nodeTlsReject: 0 

machineSensor1:
  port: 80

machineSensor2:
  port: 80
  sensorTemperature: true

kafka:
  broker:
    uri: "kafka-cluster-kafka-bootstrap.factory-lake.svc:9092" 
    topic:
      temperature: "manuela-factory.iot-sensor-sw-temperature"
      vibration: "manuela-factory.iot-sensor-sw-vibration"

